// <auto-generated />
using HGame01Server.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HGame01Server.Migrations
{
    [DbContext(typeof(GameDbContext))]
    partial class GameDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("HGame01Server.Models.GameUser", b =>
                {
                    b.Property<long>("uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("uid"));

                    b.Property<string>("createdAt")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("equipmentStorageCapacity")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("profileId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("uid");

                    b.ToTable("users");
                });

            modelBuilder.Entity("HGame01Server.Models.GameUserCharacter", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("id"));

                    b.Property<string>("acquiredAt")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("characterTag")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("isActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<long>("uid")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.ToTable("user_characters");
                });

            modelBuilder.Entity("HGame01Server.Models.GameUserCurrency", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("id"));

                    b.Property<long>("amount")
                        .HasColumnType("bigint");

                    b.Property<int>("currencyType")
                        .HasColumnType("int");

                    b.Property<long>("uid")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex("uid", "currencyType")
                        .IsUnique()
                        .HasDatabaseName("IX_user_currencies_uid_currencyType");

                    b.ToTable("user_currencies");
                });

            modelBuilder.Entity("HGame01Server.Models.GameUserEquipment", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("id"));

                    b.Property<string>("acquiredAt")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("equipmentTag")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("equippedCharacterTag")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("isEquipped")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("slot")
                        .HasColumnType("int");

                    b.Property<long>("uid")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex("uid")
                        .HasDatabaseName("IX_user_equipments_uid");

                    b.ToTable("user_equipments");
                });

            modelBuilder.Entity("HGame01Server.Models.GameUserMail", b =>
                {
                    b.Property<string>("mailId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("claimedAt")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("expireAt")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("iconAtlas")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("iconKey")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("mailKind")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("rewardsJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("senderType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("sentAt")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("titleKey")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("uid")
                        .HasColumnType("bigint");

                    b.HasKey("mailId");

                    b.HasIndex("expireAt")
                        .HasDatabaseName("IX_user_mails_expireAt");

                    b.HasIndex("uid", "claimedAt")
                        .HasDatabaseName("IX_user_mails_uid_claimedAt");

                    b.ToTable("user_mails");
                });

            modelBuilder.Entity("HGame01Server.Models.GameUserQuestEventApplied", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("id"));

                    b.Property<string>("appliedAtUtc")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("eventClientId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<long>("uid")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex("appliedAtUtc")
                        .HasDatabaseName("IX_user_quest_events_applied_appliedAtUtc");

                    b.HasIndex("uid", "eventClientId")
                        .IsUnique()
                        .HasDatabaseName("IX_user_quest_events_applied_uid_eventClientId");

                    b.ToTable("user_quest_events_applied");
                });

            modelBuilder.Entity("HGame01Server.Models.GameUserQuestInstance", b =>
                {
                    b.Property<string>("instanceId")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("containerStableId")
                        .HasColumnType("int");

                    b.Property<string>("expiresAtUtc")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("issuedAtUtc")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("lastUpdatedUtc")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("questDataId")
                        .HasColumnType("int");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("subProgressJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("uid")
                        .HasColumnType("bigint");

                    b.HasKey("instanceId");

                    b.HasIndex("uid")
                        .HasDatabaseName("IX_user_quest_instances_uid");

                    b.ToTable("user_quest_instances");
                });

            modelBuilder.Entity("HGame01Server.Models.GameUserShopPurchase", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("id"));

                    b.Property<string>("purchasedAt")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("shopItemId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<long>("uid")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex("uid", "shopItemId")
                        .HasDatabaseName("IX_user_shop_purchases_uid_shopItemId");

                    b.ToTable("user_shop_purchases");
                });
#pragma warning restore 612, 618
        }
    }
}
